### ISSUE TITLE
dict2xml always sorts the keys before creating XML file..

### ISSUE THREAD

**Issue by akr8986** [delfick/python-dict2xml#11]
Hi,

I can see from the dict2xml code that the keys of the input dict (and subdicts too..) are always sorted before creating an xml file..

I am not sure why this behavior was choosen..

i my case the order of the attributes matters and it makes dict2xml not usable for me..

The input to dict2xml in my case is an OrderedDict()... 

I think its better to make sorting an optional/controllable feature through some input flag...

**Comment by delfick** [comment]
hello!

The reason it's sorted is so my tests work (makes it deterministic).

I've created a commit that doesn't do that if the mapping is `isinstance(data, collections.OrderedDict)` and so should solve your problem :)

I've released a new version, 1.5 to pypi with this change.

Please don't hesitate to mention any other issues you find :)

Stephen.

**Comment by akr8986** [comment]
Thanks a lot Del. :)

**Comment by delfick** [comment]
No probs :)

**Comment by timoschd** [comment]
Thank you. Someone should update the documentation to include this

**Comment by delfick** [comment]
@timoschd reasonable point! https://github.com/delfick/python-dict2xml/commit/a0d1313b96b67b4a8df194d14b6d69a14612b80d
