### ISSUE TITLE
Self closing tags?

### ISSUE THREAD

**Issue by Tobeyforce** [delfick/python-dict2xml#17]
Is it possible to have the parse function return a self closing tag, meaning it's empty?
E.g {"empty": ""} or {"empty": None} right now becomes
`<empty></empty> and <empty>None</empty>` but I'd like to be able to receive `<empty/>`, a self closing tag. I realize however that selfclosing tags and empty tags might be the same thing in XML.

**Comment by delfick** [comment]
Do you have example input/output to describe what you mean?

**Comment by Tobeyforce** [comment]
Sorry I forgot to format the code in the comment so it disappeared, please have a look now :-)

**Comment by delfick** [comment]
yes, your first comment looks more complete now :)

I see what you mean now. I'll find some time later (maybe today, maybe
during week, we'll see) and see what I can do.

I imagine it wouldn't be too hard. Probably add an option that defines what
values create such tags.

**Comment by delfick** [comment]
@Tobeyforce would this solve your needs ? https://github.com/delfick/python-dict2xml/commit/7ee3ae9bae2140d23011956923cdb7105d26de50

**Comment by delfick** [comment]
@Tobeyforce ?

**Comment by Tobeyforce** [comment]
> @Tobeyforce ?

Let me get back to you soon, caught covid but will look at the commit as soon as I'm well :)

**Comment by delfick** [comment]
super sorry to hear that. take your time!

**Comment by amospalla** [comment]
Had the same need as Tobeyforce.

Using this commit and suddenly I've got self closing tags, which I needed for a project too.

(:

**Comment by delfick** [comment]
hehehe, cool. I say I'll merge this later tonight, can always make extra changes in other PRs later if needed :)

**Comment by delfick** [comment]
@amospalla @Tobeyforce ok, that commit is released in 1.7.1

Don't be afraid to ask for any other adjustments :)
