### ISSUE TITLE
Please include tests and examples in sdist

### ISSUE THREAD

**Issue by kitterma** [delfick/python-dict2xml#19]
It would be nice to be able to run the tests from the pypi tarball for downstream users/distributors.  Having the example would also be helpful.  Here's the change:

```
diff --git a/MANIFEST.in b/MANIFEST.in
index a5021c6..c9ba80b 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -1,2 +1,4 @@
 include README.rst
 include LICENSE
+include tests/*
+include tests/examples/*
```

**Comment by delfick** [comment]
it's before 8am in this timezone and I managed to push the version bump commit to the branch rather than main hahha. Anyway, I pushed it to main and have now released 1.7.2 :)

**Comment by kitterma** [comment]
Excellent.  Thanks.

Scott K

**Comment by delfick** [comment]
You're welcome!

**Comment by kitterma** [comment]
FYI,

The tests now run in Debian's CI:

https://ci.debian.net/packages/p/python-dict2xml/

Thanks again.

**Comment by delfick** [comment]
very cool, thanks :)
