### ISSUE TITLE
"No matching distribution" when trying to install `dict2xml` with `pip` and `--only-binary=:all:`.

### ISSUE THREAD

**Issue by St333p** [delfick/python-dict2xml#21]
I have encountered a weird issue when trying to install `dict2xml` with `pip` while specifying the `--only-binary=:all:` flag.
    
The reason why I'm doing this is that I need to build a package while specifying a target platform (with `--platform`), which requires to specify the above flag; dict2xml is the only dependency which gives problems in this regard. 

I have not found any generic information about this issue and I can only see it happen with dict2xml, so I assumed it's a project-specific limitation, but I could be wrong on this.  

### Details

    $ pip install --only-binary=:all: dict2xml
    ERROR: Could not find a version that satisfies the requirement dict2xml (from versions: none)
    ERROR: No matching distribution found for dict2xml

    $ pip install dict2xml
    Collecting dict2xml
    Installing collected packages: dict2xml
    Successfully installed dict2xml-1.7.2
    
I reproduced this with:
 - python 3.8 and 3.9
 - pip 22.2.2 and 23.0.1

**Comment by delfick** [comment]
That's because I only push up a source bundle. I'll have a look later at pushing up a wheel as well. Hopefully should find time by the weekend.

**Comment by St333p** [comment]
That would be nice. 
For now, as a workaround if anybody else bumps into this, we install `dict2xml` separately from other requirements using `--no-deps` instead of `--only-binary=:all:`.

**Comment by delfick** [comment]
I've released a new version that includes a wheel and so it should work now :)
<img width="1116" alt="Screenshot 2023-02-25 at 1 15 36 pm" src="https://user-images.githubusercontent.com/109301/221330921-0766751e-741f-4edf-9479-0dfa03d18e41.png">
