### ISSUE TITLE
Ordered dictionary not working

### ISSUE THREAD

**Issue by stuchalk** [delfick/python-dict2xml#22]
I've made the dictionary that I send to dict2xml an OrderedDict but it does not retain the order of elements in the dictionary. Here is my code and attached are the XML and JSON outputs (in a zip file) I am currently getting using this code.  The JSON shows how I would like it to be organized in the XML file.

![3829](https://user-images.githubusercontent.com/540150/235724958-6cd7a2b0-0ee5-4e57-b51a-afb53f1fbaa3.jpg)
[3829.zip](https://github.com/delfick/python-dict2xml/files/11375422/3829.zip)

**Comment by delfick** [comment]
does it work if you use
```
dout.update({'compilation': OrderedDict()})
```
?

**Comment by stuchalk** [comment]
Yep, that fixed it.  I thought it should be at the top but that is not the case.  Thanks!

**Comment by delfick** [comment]
:)
