### ISSUE TITLE
Maintain dict ordering in Python >= 3.6

### ISSUE THREAD

**Issue by Finndersen** [delfick/python-dict2xml#24]
Dictionaries maintain their ordering in Python >= 3.6, so there's no need to use `OrderedDict`. I think the implicit sorting would be unexpected/undesirable behaviour for most people. 

It would be good to [add a check](https://github.com/delfick/python-dict2xml/blob/aa88f3b69bd0c5b2331ab6b450f2bb9b9f0db5f7/dict2xml/logic.py#L146) to skip sorting the input dictionary. or Python version >= 3.6.

**Comment by delfick** [comment]
fixed in https://github.com/delfick/python-dict2xml/pull/25 and released in version 1.7.5 :)

**Comment by Finndersen** [comment]
Nice! 👍
