### ISSUE TITLE
DataSorter is not working

### ISSUE THREAD

**Issue by qiisqwww** [delfick/python-dict2xml#26]
As it was mentioned in #25, if I don't want to sort my data i should use data_sorter this way:

![image](https://github.com/user-attachments/assets/4b988c6b-124a-4d07-ad4c-5822123b875c)

I guess i do the same:

![image](https://github.com/user-attachments/assets/3908b34d-8206-42dc-9358-5d5ad7624d70)

But I'm getting an error: `TypeError: Converter.__init__() got an unexpected keyword argument 'data_sorter'`
I guess it happens cuz data_sorter is expected in `build()` function, not in `Сonverter.__init__().` Although as we can see [here](https://github.com/delfick/python-dict2xml/blob/main/dict2xml/__init__.py), all *args and **kwargs will be put into the `Converter().__init__()`

**Comment by delfick** [comment]
oops, sorry about that, I have released 1.7.6 with a fix @qiisqwww
